server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://60.205.226.163:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username : root
    password : admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 60.205.226.163
    password: 123456
    client-name: c1

mybatis:
  mapper-locations: classpath:/mappers/*.xml
